### ISSUE TITLE
Investigate and fix test failures introduced by merging the ledger protocol

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-aea#348]
https://github.com/valory-xyz/open-aea/pull/345#discussion_r982114517

**Comment by Karrenbelt** [comment]
The issue is the result of a change in the dialogues.

Initially this was as follows
https://github.com/valory-xyz/open-aea/blob/5565df58b91a191eb310bd3104653b69d39fc8aa/packages/valory/protocols/ledger_api/README.md?plain=1#L67-L80
which contains the following sequence: 
```
get_raw_transaction -> raw_transaction -> send_signed_transaction -> transaction_digest -> get_transaction_receipt -> transaction_receipt
```

currently, however, this sequence is broken up into atomic request-response pairs
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/packages/valory/protocols/ledger_api/README.md?plain=1#L69-L82

and therefore the sequence specified in the `TestLedgerApiHandler` is no longer valid
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/packages/fetchai/skills/erc1155_deploy/tests/intermediate_class.py#L254-L279
