### ISSUE TITLE
Fix flaky `testget_or_create_cli_config_bad_yaml` tests

### ISSUE THREAD

**Issue by angrybayblade** [valory-xyz/open-aea#366]
https://github.com/valory-xyz/open-aea/pull/362#issuecomment-1274288147

**Comment by Karrenbelt** [comment]
please be more descriptive and add a snippet of the error at minimum since CI runs expire.

This is effectively a `TimeoutError`. We call `queue.Queue.get()` here and the timeout is used is `10`s so that is unlike to be the issue.
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/helpers/async_friendly_queue.py#L61-L71
Hence we may look at the Multiplexer.put method invoke prior to it
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/multiplexer.py#L846-L855
which delegates to the AsyncMultiplexer.put method using the ThreadedAsyncRunner to make a thread safe call to the builtint `Queue.put_nowait`.
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/multiplexer.py#L723-L735
Noticeably a timeout for the return value of the future's result has been outcommented here in a piece of code last edited by @solarw 3 years ago, in a commit for which there is not previous version to be found via [git blame](https://github.com/fetchai/agents-aea/blame/main/aea/multiplexer.py). I don't think this is needed and the outcommented piece of code may in that case be deleted.
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/multiplexer.py#L855

In summary: I don't think there is an issue with `.put` and `.get` methods. We start the test, status is_connected, we attempt to send the message via put (queue empty) with the Threadrunner we call Queue.put -> put_nowait(). And basically get it's the same story... get with block and timeout --> .. --> .. --> Queue.get with block and timeout. 

I suggest we ask @solarw to have a look at this, as he is better acquainted with the code and concurrent programming in general. 

Tiny insignificant detail I'll leave here as well, annotation here should be `Coroutine` instead of `Awaitable`
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/helpers/async_utils.py#L258
https://github.com/valory-xyz/open-aea/blob/bbd8fc00e1c5ffe5c1147c2d3e342a3ecf7645cf/aea/helpers/async_utils.py#L328

[failure.log](https://github.com/valory-xyz/open-aea/files/10144092/failure.log)

**Comment by Karrenbelt** [comment]
I believe this has been addressed in https://github.com/valory-xyz/open-aea/pull/369
