### ISSUE TITLE
Flaky tests: `test_config.py::TestConfigGet::test_get_skill_name`

### ISSUE THREAD

**Issue by Karrenbelt** [valory-xyz/open-aea#392]
CI run: https://github.com/valory-xyz/open-aea/actions/runs/3296676265/jobs/5436718934

```
FAILED tests/test_cli/test_config.py::TestConfigGet::test_get_skill_name - AssertionError
```

[failure.log](https://github.com/valory-xyz/open-aea/files/9838848/failure.log)

**Comment by angrybayblade** [comment]
I'm closing this issue because if you look at the error log
```
    def test_get_skill_name(self):
        """Test getting the 'dummy' skill name."""
        result = self.runner.invoke(
            cli,
            [*CLI_LOG_OPTION, "config", "get", "skills.dummy.name"],
            standalone_mode=False,
        )
        assert result.exit_code == 0
>       assert result.output == "dummy\n"
E       AssertionError: assert '' == 'dummy\n'
E         - dummy

D:\a\open-aea\open-aea\tests\test_cli\test_config.py:87: AssertionError
---------------------------- Captured stdout call -----------------------------
dummy
```

The error says that `dummy` is missing from the `result.stdout` where it's clearly there in the output captured by pytest. This happens because output capture in the the click CLI runner does not work everytime but the message is still there. We already have a ticket for investigating or replacing this broken mechanism. Please wait until a test fails multiple times before creating an issue for the same.

**Comment by Karrenbelt** [comment]
At a minimum you can link the issue that subsumes this failure. Furthermore, you may point to where precisely the output is present in pytest such that the person who opened to issue doesn't need to go dig through the logs in order to try to find it themselves. I had a brief look in the raw logs just again now and I don't see it. 

I think the way we check for output in the `stdout` is the issue and have an alternative suggestion.
